name: Try out running a thing in python
on: [push]
jobs:
    test-job:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2

            - uses: actions/setup-python@v1
              with:
                  python-version: 3.7

            - run: pip install github3.py requests
            - run: sudo apt-get update && sudo apt-get install -y pandoc
