name: Try out event triggers
on:
    schedule:
        - cron: "0 0 * * *"
    push:
        branches:
            - master
    create:  # This should cause the action below to execute whenever a tag is added on master.
        branches:
            - master

jobs:
    hello-world:
        name: "Hello World!"
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - run: echo "Hello, world!"
